# ==========================
# Configuración de PostgreSQL
# ==========================
spring.datasource.url=jdbc:postgresql://levelupgamerweb-db.c6efk2vlrfmn.us-east-1.rds.amazonaws.com:5432/levelupgamer
spring.datasource.username=postgres
spring.datasource.password=walala321.

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Para evitar problemas de zona horaria
spring.jackson.time-zone=America/Santiago

# Puerto del servidor (opcional)
server.port=8080
